# fly.toml app configuration file generated for matts-mangos on 2023-07-06T15:56:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "matts-mangos"
primary_region = "dfw"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
